### ISSUE TITLE
input exception

### ISSUE THREAD

**Issue by mindonghak** [sungjk1999/lotto-number-analysis#5]
yy-mm-dd이전까지만 출력해야 하는데,
연도 형식이 yy-mm-dd라서 2000년대 이전 입력하면 그냥 모든 연도가 다 나옴.
굳이 예외처리를 해야 하나 싶기도 하고 
만약 한다면 입력을 그냥 안 받는 것도.... 어차피 90년대 말부터 시작인 것 같던데

**Comment by sungjk1999** [comment]
입력 `yy-MM-dd` 부터 최근 로또 추첨까지 나와야하니까 최초 로또 추첨일보다 과거의 시간 입력이 들어오면 전부 출력하고, 최근 로또 추첨일보다 나중 시간이 들어오면 가장 최근것만 보여주는식으로 하면 될 것 같음

**Comment by mindonghak** [comment]
어제 졸려서 저 글이 좀 이상하게 써졌는데 기본적인 입력 예외처리는 다 해놨음

yymmdd이전까지 출력이라고 써있어서 그렇게 해놨는데 (문자열 등 이상한 형식도 다 걸러짐)

예를들어 88-10-10이러면 1988인지 2088인지 구분을 못해서 2088로 생각하고 전체가 다나온다는 의미였어 !

**Comment by sungjk1999** [comment]
아 그러면 88-10-10 인 경우에는 88이면 1988 혹은 2088일테니까, 현재 연도를 `datetime` 로 받아서 더 작은 값을 valid하게 보고 처리하면 될 듯? 애초에 1888 년도랑 1988 년도 같은게 구분되야하면 입력을 yy로 줬으면 안되고 yyyy로 줬을 테니까 엄밀하게 안하고 대충 맞춰주면 될 것 같아.
