### ISSUE TITLE
실행시간 너무 긺

### ISSUE THREAD

**Issue by mindonghak** [sungjk1999/lotto-number-analysis#6]
거의 회당 0.5초가 걸릴 정도로 오래 걸림 
이건 좀 문제가 있어 보이는데....

**Comment by sungjk1999** [comment]
이게 클릭을 직접하는 방식이라 그런지 나도 돌리다보니 느려졌음. 살펴보니 이게 전체 데이터를 한번에 볼 수있는 창이 있긴한데 이걸로 어떻게 가능한지 해봐야할것 같아. 아니면 그냥 역대 번호 한번 긁은거 db에 저장해두고 쓰게해야할거같은데...

**Comment by mindonghak** [comment]
아 그런창이있어?
전체 엑셀로 다운받을수는 있던데
 근데 크롤링을 했다는게 중요한거일려나 그건 좀 의문이군

**Comment by sungjk1999** [comment]
그 연도별로 구간 설정해서 한번에 크롤링가능할듯?
